all:
  hosts:
    node1:
      ansible_host: "{{ node1_ip }}"
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/practice.pem
    node2:
      ansible_host: "{{ node2_ip }}"
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ~/.ssh/practice.pem

  children:
    webservers:
      hosts:
        node1:
        node2:
